title = "new dashboard"

[[row]]
title = "DISKWRITE"
    [[row.panel]]
        stack = true
        [[row.panel.metric]]
            measurement = "DISKWRITE"
            hosts   = ["lpar1"]
            fields = ["hdisk1", "hdisk2"]

    [[row.panel]]
        stack = true
        [[row.panel.metric]]
            measurement = "DISKWRITE"
            hosts = ["lpar2"]
            fields = ["hdisk3", "hdisk4"]

[[row]]
title = "DISKREAD"
    [[row.panel]]
        [[row.panel.metric]]
            measurement = "DISKREAD"
            hosts = ["lpar1"]
            fields = ["hdisk1", "hdisk2"]
    [[row.panel]]
        [[row.panel.metric]]
            measurement = "DISKREAD"
            hosts = ["lpar2"]
            fields = ["hdisk3", "hdisk4"]
